import {
  Montserrat,
  Playfair_Display,
  Source_Code_Pro,
} from "next/font/google";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "@/components/convex-client-provider";

const fontSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html
        lang="en"
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} h-full antialiased min-h-[calc(100vh-2rem)] flex flex-col gap-4`}
      >
        <body className="min-h-full flex flex-col">
          <ConvexClientProvider>
            <main className="px-2 md:px-4 grow flex flex-col">{children}</main>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
